Add choicesjs stencil plugin
adidas/adidas-yarn-plugin-choicesjs-stencil pull request #1
Opened 2018-10-10 15:31 UTC by moelders

# 1.0.0

- First release of `@adidas/yarn-plugin-choicesjs-stencil` plugin for adidas YARN Design System library.

2018-10-10 15:43 UTC, moelders commented
Pending to be tested with adidas YARN.

2018-11-07 16:16 UTC, RecuencoJones requested changes

2018-11-07 16:16 UTC, RecuencoJones commented on webpack.config.js
> +    path: path.resolve(cwd, './dist'),
Can we use `__dirname` instead of `cwd`?

2018-11-08 07:21 UTC, RecuencoJones approved these changes
LGTM

2018-11-08 07:21 UTC, merged